site_name: MASSIVE
site_url: https://mitchso.github.io/MASSIVE
repo_url: https://github.com/mitchso/MASSIVE
repo_name: mitchso/MASSIVE

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences

nav:
  - Home: index.md
  - Guides:
    - Getting started: guides/overview.md
    - Input data formatting assistance: guides/data_formatting.md
    - Planning an experiment: guides/plan-experiment.md
    - Analyzing an experiment: guides/analyze-experiment.md
    - Scoring enzymes: guides/score-enzymes.md
  - API:
    - Analytes: api/analytes.md
    - Sample: api/sample.md
    - Collections: api/collections.md
    - Scoring: api/scoring.md
    - Metadata: api/metadata.md
    - Helper: api/helper.md
